language: python
python:
- '3.4'
- '3.5'
- '3.6'
env:
- PYPI_URL=https://testpypi.python.org/pypi
install:
- pip install --upgrade pip
- pip install coveralls==1.*
- pip install -r requirements.txt
- pip install .
script: make lint && make test
after_success:
  coveralls
deploy:
  - provider: pypi
    username: dansondergaard
    server: $PYPI_URL
    password:
      secure: xoA/xtueC8420iENzNrhIfo+FyxAVG5DhesUa6AxGk8qvR7/DqVU5Rsuj0r0f+l5LwoXvBLCisl2rAbQu+LjZ2jPU2UKKsae0P6V9JInHFf5i2Y7VeGkUIrB5vsWvyPLbTCYUqJwtxVlvGI$46houxpM51gf+lQqP74abIjMZ8O7EycOXprgVWDCuLAlp2tS0yPPmiAiAa5LKiLNkhSaBbHB3Dx2y+oDbtx4OzECUr1LpaH1GeU2ztWjC9kr8ySKlNXTr9C+EZ2BZhRMZyoI/eNo1uVmU6I5Nyvyazf2017wF+oHMY83b6AwKsIpSRa5De/cI8+Ggzca8XHa1j3Na2b4aCKZ3Sur0CLxeHgw+7aLWUkj8v292IhEQl6bU0AU3tGXIPKFuU3UB+e/sHprVYtkBxtYVdnsoJzgdO/lPMiW4pVwV3EOswCO80ldRHwD8ayk901u/9BeeBZ9Xe5OFXA6ESsMzBGOufttJBQ5YkAyp/YYVtsWOPS1C087n5VQ5pZLZ8AWmLvnWgJ2T0IddtSMH+5HxojfbPlAaGaH1wdQV4jCvRwuDPPgtN0Jg2xXGPPBbpUdKRNEmMGSOHwXyzgsZ7XJR2VsfKUcnpKgvAwmsodOi1mcdCwWIL1a08KjkXElPOA4G05N8AP7kCUKg4/Jatd/XBq+2NdxkdDLJOys=
    distributions: sdist bdist_wheel
    skip_cleanup: true
    skip_upload_docs: true
    on:
      branch: master
after_deploy: build_conda.sh
