language: python
matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.8-dev
install: make init
script: make test
after_success:
  - make coverage-ci

