language: python
sudo: required
addons:
  hosts:
    - cibox
  hostname: cibox
python:
  - "3.4"
  - "3.5"
install:
- make init
- make init-slurm
- pip install coveralls==1.1
script: make test
after_success:
- coveralls
