language: python
sudo: false
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
install: make init
script: make test
after_success:
  - make coverage-ci
deploy:
  - provider: script
    script: make publish
    skip_cleanup: true
    on:
      branch: master
      tags: true
