language: python
python:
- 3.4
- 3.5

# Setup anaconda
before_install:
- wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- ./miniconda.sh -b
- export PATH=$HOME/miniconda3/bin:$PATH
- conda update --yes -q conda
- conda config --set always_yes true
- conda config --set anaconda_upload no
- conda config --add channels dansondergaard

# Install packages
install:
- conda install -q python=$TRAVIS_PYTHON_VERSION pip conda-build anaconda-client
- conda build conda/
- conda install --use-local gwf
- pip install coveralls==1.*

# Run test
script:
- make test

deploy:
- provider: script
  skip_cleanup: true
  script: chmod +x deploy_anaconda.sh && deploy_anaconda.sh
  on:
    tags: true
