language: python
dist: bionic
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"
before_install:
  - pip install poetry
install:
  - make init
script:
  - make test
after_success:
  - poetry run coveralls

