language: python

sudo: false

python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

install: "make init"

script: "make test"

after_success:
  - coveralls
  - chmod +x ./conda/deploy_conda.sh

deploy:
  - provider: pypi
    username: dansondergaard
    password:
      secure: XuSKTx3WoBi8wLSCIX/Y4w0D3K2WqmCLVPYtaSIezvydtKg5wijdTh/iiyXq8GrBqYaOHzk2tJz9YeuHoIgD89eQJu+OJULyM0YlWOzYyu0hNpUjapBh/fSLX6vfNOuTu94vealxhS4veR3MRvssbFKps54EItmFXzV+K+6xnScppiNxz0T/WuKUSM2EF+2eMzrwKb0VaQifX5nwsozulDx/yjvFG30VNNlPsvSjvxt+j/aMtPFyRbq3QGtGs11VPp8nGz87GRbAmN72AeK5BsDi5nTm70zilVXqoZSdSYzX4eIiPWNzISiJfG4XQF3jX7LAyLGQfsytLoT3sPMV+UA+/KoFAvU2o7W41FVszwIPcc4JU2I+sjbKEkRkhOn9GvD2Om9pv0Jp6top7PSmqUM9xSkT0VvS4VvU5IaKFcnlQj8y03nhlmDTuzdNtGQMiwYdgc/i1zObo6CYTDjZZ1SxdNZiqXf3vXxWLg7JDKqRRLoYULBnR4pGHkIVP1x5MPAZOtoUKVK/nWw+JsUsSSC8MEVDem20JlG6nJaXICG0BNCaW91FYkWSLCvvbiTase5lHBBZsA4dAXbbI3dp1T1kcWf5f9AZKOVdC2wxe6ZOMa+609i+FmuU09MbZ39O4UJcNgPECRJcCmumNMkRrZ+LbDYzuAMI5g96IbQk0SE=
    distributions: sdist bdist_wheel
    skip_cleanup: true
    skip_upload_docs: true
    on:
      tags: true

  - provider: script
    script: "./conda/deploy_conda.sh"
    skip_cleanup: true
    skip_upload_docs: true
    on:
      tags: true
