language: python
python:
- '3.4'
- '3.5'
- '3.6'
- pypy3
install:
- pip install coveralls==1.*
- pip install --user -r requirements.txt
- pip install .
script: make test
deploy:
  provider: pypi
  username: dansondergaard
  server: https://testpypi.python.org/pypi
  password:
    secure: EUIG+e1RTg/U1uqzEQB0IItiljiDDc5aR69ViLJLM5g3n0rfMLygx7NVl9FQwN2jY8AEkjM787Qcdws9TzFXhxVgXTtIYKpVHIZ9ZlevDgif6cP4mrXVqtiXqhWlbKhaqwOtqywSdMkOUo3Fo9ZMfC082Lrn8usVga8zFZ8Nagtsb8VeMV5Ugx/ZnTuTKh7msb5IlWjqRCah3xIdO+t9nJ4Z1/doGeHpD8PiD+9GvnJTDgJlj/AMeSx4TO66bnhdR0DmXlq90bJuVJ2I0jTpi+On+ZnPqcC0RNdUw2EZEwTrxp/GtXNxANhgRDSunznPRhlk0/946mJbBg2+e5s1VY7ZE65CmWRiexUs2GgCbgpMHzjYG4Q9bYzwdIOAht2bxkWtWILEluzVG0Pub6TySHN3mx6GZi9R6VzS+uh/EOuo+/wFjc5NrTXYVzFTXFdCO52ixH0lu7S+xkgmYgCoummE4w+O1PaGLBJndE3w3rDCvALl1gLqvKVH2vqibgt5v5qd1JtBcy+SD26QqH7lSQq6ukOrxriQmkVW8FBj9/n17MptROSt3TjOys9fgt+KEIDbskMX7rv3kjUIV3e0ovo85uG8C2byg138zbrDAygbTKTeKAjxAebIPPcZb6APVrtOHaB0r0E2mKsEELPHhh/yga9R4da//CHQqNWguq0=
