{% set data = load_setup_py_data() %}

package:
  name: gwf
  version: {{ data.get('version') }}

source:
  path: ../

build:
  entry_points:
    - gwf = gwf.cli:main

requirements:
  build:
    - python {{ python }}
    - setuptools
    - click >=6.6
    - click-plugins >=0.2.2

  run:
    - python {{ python }}
    - setuptools
    - click >=6.6
    - click-plugins >=0.2.2

test:

  imports:
    - gwf
    - gwf.backends
    - gwf.plugins

  commands:
    - gwf --help

about:
  home: http://gwf.readthedocs.io/
  license: GNU General Public License v3 (GPLv3)
  summary: A flexible, pragmatic workflow tool.
  license_family: GPL3
