package:
  name: gwf
  version: 1.4.0

source:
  url: https://github.com/gwforg/gwf/archive/v1.4.0.tar.gz

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - gwf = gwf.cli:main

requirements:
  build:
    - python >=3.5
    - setuptools

  run:
    - python >=3.5
    - setuptools
    - click >=6.6
    - click-plugins >=0.2.2
    - colorama # [win]

test:
  imports:
    - gwf
    - gwf.backends
    - gwf.plugins

  commands:
    - gwf --help

about:
  home: http://gwf.readthedocs.io/
  license: GNU General Public License v3 (GPLv3)
  summary: A flexible, pragmatic workflow tool.
  license_family: GPL3
