{% set name = "gwf" %}
{% set version = "1.6.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 28e17099b0219d047a63a37f78f861fff847947fa40101eb2764b4daeb36ead9

build:
  number: 0
  noarch: python
  entry_points:
    - gwf = gwf.cli:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - click
    - click-plugins
    - pip
    - python
    - setuptools
    - pytest-runner
  run:
    - click
    - click-plugins
    - python
    - setuptools

test:
  imports:
    - gwf
    - gwf.backends
    - gwf.plugins
  commands:
    - gwf --help

about:
  home: http://gwf.app/
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3
  summary: A flexible, pragmatic workflow tool.
  doc_url: https://gwf.app/
  dev_url: https://github.com/gwforg/gwf

extra:
  recipe-maintainers:
    - dansondergaard
