package:
  name: gwf
  version: "1.0b5"

source:
  path: ../

build:
  noarch_python: True
  preserve_egg_dir: False
  entry_points:
    - gwf = gwf.cli:main

requirements:
  build:
    - python
    - setuptools
    - click >=6.6
    - click-plugins >=0.2.2
    - statusbar >=0.1.4
    - pytest-runner

  run:
    - python
    - setuptools
    - click >=6.6
    - click-plugins >=0.2.2
    - statusbar >=0.1.4

test:
  imports:
    - gwf
    - gwf.backends
    - gwf.plugins

  commands:
    - gwf --help

  requires:
    - pytest

about:
  home: http://gwf.readthedocs.io/
  license: GNU General Public License v3 (GPLv3)
  summary: 'A flexible, pragmatic workflow tool.'
  license_family: GPL3
