{% set name = "gwf" %}
{% set version = "1.6.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 216c5ca0fea5172d6d2a483a871d670757c254dea9d6099a8d8e24d062b0d485

build:
  number: 0
  noarch: python
  entry_points:
    - gwf = gwf.cli:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - click
    - click-plugins
    - pip
    - python
    - setuptools
    - pytest-runner
  run:
    - click
    - click-plugins
    - python
    - setuptools

test:
  imports:
    - gwf
    - gwf.backends
    - gwf.plugins
  commands:
    - gwf --help

about:
  home: http://gwf.readthedocs.io/
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3
  license_file: ../LICENSE
  summary: A flexible, pragmatic workflow tool.
  doc_url: https://gwf.readthedocs.io
  dev_url: https://github.com/gwforg/gwf

extra:
  recipe-maintainers:
    - dansondergaard
