{% set name = "gwf" %}
{% set version = "1.5.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b36d7f37be2a2d81cb849d7556feb21e75d0ff1ba1d8b2cabaecc77ac2b38b99

build:
  number: 0
  noarch: python
  entry_points:
    - gwf = gwf.cli:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - click
    - click-plugins
    - pip
    - python
    - setuptools
    - pytest-runner
  run:
    - click
    - click-plugins
    - python
    - setuptools

test:
  imports:
    - gwf
    - gwf.backends
    - gwf.plugins
  commands:
    - gwf --help

about:
  home: http://gwf.readthedocs.io/
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3
  license_file:
  summary: A flexible, pragmatic workflow tool.

extra:
  recipe-maintainers:
    - dansondergaard
