{% set name = "gwf" %}
{% set version = "1.7.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "12c3438eaf2b86a771c511f6cdbb33e89e9da87cbb4ea7c91f384534893ff70b"

build:
  number: 0
  noarch: python
  entry_points:
    - gwf = gwf.cli:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - click >=6.0,<7.0
    - click-plugins >=1.0,<2.0
    - pip
    - python
    - setuptools
    - pytest-runner
    - poetry
  run:
    - click >=6.0,<7.0
    - click-plugins >=1.0,<2.0
    - python
    - setuptools

test:
  imports:
    - gwf
    - gwf.backends
    - gwf.plugins
  commands:
    - gwf --help

about:
  home: http://gwf.app/
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3
  summary: A flexible, pragmatic workflow tool.
  doc_url: https://gwf.app/
  dev_url: https://github.com/gwforg/gwf

extra:
  recipe-maintainers:
    - dansondergaard
